default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'postgres' } %>

development:
  <<: *default
  database: stock_app_rails_development

test:
  <<: *default
  database: stock_app_rails_test

production:
  <<: *default
  database: stock_app_rails_production
  username: stock_app_rails
  password: <%= ENV["STOCK_APP_RAILS_DATABASE_PASSWORD"] %>
